"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

from .base import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'stfout&6=qv8n_b6o3jeno4i8emxpyc4n+_bv+^pac!5bd_6(j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db',
        'USER': 'mysql_user_external',
        'PASSWORD': '123456',
        'HOST': '192.168.10.10',
        'PORT': '3306',
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'


#GOOGLE MAP API KEY
GOOGLE_MAP_API_KEY = "AIzaSyD_xtnckJYoWHSq0xJms1hAkQ0Y4KylXzc"

#AWS
AWS_ACCESS_KEY_ID = "AKIAICVV4IVJB6ED55OA"
AWS_SECRET_ACCESS_KEY = "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"
