# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:56
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'permissions': (('can_resend_sms_verification_code', 'Can resend sms verification code'), ('can_resend_email_verification_code', 'Can resend email verification code')), 'verbose_name': 'owner', 'verbose_name_plural': 'owners'},
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
