# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 01:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20170322_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$')], verbose_name='Phone number'),
        ),
    ]
