# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20170323_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='google_place_id',
            field=models.CharField(max_length=60, unique=True, verbose_name='Google place id comes from places detail api'),
        ),
    ]
