# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20170323_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lng',
            new_name='lon',
        ),
    ]
