# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import GEOSGeometry
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20170331_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='lon',
        ),
        migrations.AddField(
            model_name='place',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=GEOSGeometry('POINT(0 0)'), null=True, srid=4326, verbose_name='Longitude/Latitude on Map'),
        ),
    ]
