# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 20:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import GEOSGeometry
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20170401_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=GEOSGeometry('POINT(0 0)'), srid=4326, verbose_name='Longitude/Latitude on Map'),
        ),
    ]
