# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20170401_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='google_place_id',
            field=models.CharField(max_length=60, unique=True, verbose_name='Google place id'),
        ),
        migrations.AlterField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
