# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 20:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import GEOSGeometry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20170401_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='google_map_url',
            field=models.URLField(default=None, verbose_name='Google map url'),
        ),
        migrations.AlterField(
            model_name='place',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is this business or place still active?'),
        ),
        migrations.AlterField(
            model_name='place',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=GEOSGeometry('POINT(0 0)'), srid=4326, verbose_name='Latitude/Longitude on Map'),
        ),
    ]
